name: Deploy to Cloud Run

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy service to Cloud Run
        uses: schliflo/action-cloud-run@feature/github-deployments
        with:
          project: ${{ secrets.GCP_PROJECT }}
          service_name: story-server
          key: ${{ secrets.GCP_SA_KEY }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
