name: "Cloud Run: Delete Service"

on:
  workflow_dispatch:
  delete:

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Cloud Run: Delete Service"
        uses: schliflo/action-cloud-run@feature/github-deployments
        with:
          project: ${{ secrets.GCP_PROJECT }}
          service_name: cloud-run-action-test
          key: ${{ secrets.GCP_SA_KEY }}
          action: 'delete'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT: ${{ toJson(github.event) }}
