name: "Cloud Run: Deploy Service"

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Cloud Run: Deploy Service"
        uses: schliflo/action-cloud-run@master
        with:
          project: ${{ secrets.GCP_PROJECT }}
          service_name: cloud-run-action-test
          key: ${{ secrets.GCP_SA_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
